from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import os

def create_defense_workflow_report():
    doc = Document()

    # --- STYLE SETUP ---
    style = doc.styles['Normal']
    font = style.font
    font.name = 'Calibri'
    font.size = Pt(11)

    # --- TITLE ---
    title = doc.add_heading('Detailed Implementation Workflow: Defensive Detection Module', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # --- OVERVIEW ---
    doc.add_heading('Overview', level=1)
    doc.add_paragraph(
        "The Defensive Module operates as an automated 'Security Operations Center' (SOC) in a box. It is designed "
        "to ingest adversarial samples generated by the Offensive Module and determine their risk level using a "
        "parallel analysis pipeline. This workflow ensures that every email is checked for technical red flags "
        "and deeper psychological manipulation."
    )

    # --- PHASE 1 ---
    doc.add_heading('Phase 1: Zero-Trust Ingestion (The "Inbox Scanner")', level=1)
    doc.add_paragraph(
        "To simulate a real corporate email gateway, the system must constantly monitor the sandbox environment."
    )
    doc.add_paragraph("The Source:", style='Heading 2')
    doc.add_paragraph(
        "The module scans the 'data/mock_inbox/' directory, where the Offensive Module 'delivers' its phishing samples. "
        "Each email is stored as a JSON object containing the subject, body, and metadata."
    )
    doc.add_paragraph("The Logic (detector_engine.py):", style='Heading 2')
    doc.add_paragraph("• Performs periodic polling of the inbox directory.", style='List Bullet')
    doc.add_paragraph("• Deserializes JSON payloads into a structured format for analysis.", style='List Bullet')
    doc.add_paragraph("• Sanitizes input to prevent code injection during the analysis phase.", style='List Bullet')

    # --- PHASE 2 ---
    doc.add_heading('Phase 2: Heuristic Scoping (The "Technical Filter")', level=1)
    doc.add_paragraph(
        "Before using expensive AI resources, the system runs high-speed deterministic checks."
    )
    doc.add_paragraph("The Logic (heuristic_analyzer.py):", style='Heading 2')
    doc.add_paragraph(
        "• Pressure Detection: Uses regex clusters to identify 'Urgency' (e.g., immediate, suspension) and 'Authority' (e.g., HR Policy, Mandatory) triggers.", 
        style='List Bullet'
    )
    doc.add_paragraph("• Link Profiling: Extracts URLs and compares them against the 'Golden Domain' (enron.com). It flags any brand-spoofing attempts.", style='List Bullet')
    doc.add_paragraph("• IP Checker: Detects the use of raw IP addresses in links, a common tactic in automated phishing.", style='List Bullet')

    # --- PHASE 3 ---
    doc.add_heading('Phase 3: Cognitive Analysis (The "Social Engineering Radar")', level=1)
    doc.add_paragraph(
        "Modern phishing bypasses technical filters by being well-written. We use LLMs to detect the 'Psychology' of the attack."
    )
    doc.add_paragraph("The Logic (llm_classifier.py):", style='Heading 2')
    doc.add_paragraph("• Tactic Identification: Groq (Llama-3.3) analyzes the email for triggers like Fear, Greed, or Curiosity.", style='List Bullet')
    doc.add_paragraph("• Contextual Reasoning: Evaluates if the tone (Low vs. High Urgency) matches the purported sender's identity.", style='List Bullet')
    doc.add_paragraph("• Reasoning Chain: The model produces a human-readable explanation of why it flagged the email.", style='List Bullet')

    # --- PHASE 4 ---
    doc.add_heading('Phase 4: Risk Scoring & Remediation (The "Decision Engine")', level=1)
    doc.add_paragraph("The results from Heuristics and LLMs are merged into a final verdict.")
    doc.add_paragraph("The Logic:", style='Heading 2')
    doc.add_paragraph(
        "The system uses a weighted scoring model (40% Heuristic, 60% LLM) to produce a Final Risk Score (0-100).", 
        style='List Bullet'
    )
    doc.add_paragraph("• ALERT: Immediate notification for scores > 50.", style='List Bullet 2')
    doc.add_paragraph("• QUARANTINE: Isolates emails with scores between 30-50 for manual review.", style='List Bullet 2')
    doc.add_paragraph("• PASS: Normal delivery for benign-looking traffic.", style='List Bullet 2')

    # --- PHASE 5 ---
    doc.add_heading('Phase 5: Forensic Logging (The "Truth Table")', level=1)
    doc.add_paragraph("For research transparency, every detection step is recorded.")
    doc.add_paragraph("The Logic:", style='Heading 2')
    doc.add_paragraph("• Appends analysis to 'data/defense_analysis_v1.jsonl'.", style='List Bullet')
    doc.add_paragraph("• Captures 'Offensive Intent' vs 'Defensive Result' to calculate False Positive rates.", style='List Bullet')

    # --- ORCHESTRATION ---
    doc.add_heading('The Detection Flow', level=1)
    doc.add_paragraph(
        "The src/defense/detector_engine.py script synchronizes these phases:"
    )
    doc.add_paragraph("1. Ingest sample from data/mock_inbox/.", style='List Number')
    doc.add_paragraph("2. Run Heuristic pattern matching (Urgency/Links).", style='List Number')
    doc.add_paragraph("3. Invoke Groq for Social Engineering analysis.", style='List Number')
    doc.add_paragraph("4. Calculate Weighted Risk Score.", style='List Number')
    doc.add_paragraph("5. Log results and update the dissertation Truth Table.", style='List Number')

    # Save
    output_path = "Detailed_Defense_Workflow.docx"
    doc.save(output_path)
    print(f"Detailed defense workflow successfully saved to {os.path.abspath(output_path)}")

if __name__ == "__main__":
    create_defense_workflow_report()
